<?php

########################################################################
# Extension Manager/Repository config file for ext: "phonegap"
#
# Auto generated by Extension Builder 2011-10-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Phonegap',
	'description' => 'Fluid view helpers that adds support for phonegap.',
	'category' => 'fe',
	'author' => 'Tim Wentzlau',
	'author_email' => 'tim.wentzlau@auxilior.com',
	'author_company' => 'Auxilior Technology PF',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>